<?php
$servidor = '192.168.43.120';
$usuario = 'root';
$password = 'my47gmc';
$bd = 'sicys';
$db_prov = 'compras_presupuesto';
$db_prov2 = 'compras_presupuesto2';
$tbl_acc_modulo = 'acc_modulo';
$tbl_acceso = 'acceso';
$tbl_bodega = 'bodega';
$tbl_categoria = 'categoria';
$tbl_cecosto = 'cecosto';
$tbl_empresa = 'empresa';
$tbl_inventario = 'inventario';
$tbl_lista = 'lista';
$tbl_presupuesto = 'presupuesto';
$tbl_producto = 'producto';
$tbl_proveedor = 'proveedor';
$tbl_rol = 'rol';
$tbl_sublinea = 'sublinea';
$tbl_tagasto = 'tagasto';
$tbl_usuario = 'usuario';
$tbl_modulo = 'modulo';
$tbl_js_scripts = 'js_scripts';
$tbl_kardex = 'kardex';
$tbl_rol_user = 'rol_user';
$tbl_acc_emp_cc = 'acc_emp_cc';
$tbl_permiso_modulo = 'permiso_modulo';
$tbl_acc_modulo_lista = 'acc_modulo_lista';
$tbl_acc_und_vls = 'acc_und_vls';
$tbl_prehsol = 'prehsol';
$tbl_predsol = 'predsol';
$tbl_prehsol_stat = 'prehsol_stat';
$tbl_estadistica = 'estadistica';
$tbl_prehreq = 'prehreq';
$tbl_predreq = 'predreq';
$tbl_prehreq_stat = 'prehreq_stat';
$tbl_und_vls = 'acc_und_vls';
$tbl_autorizacion = 'autorizacion';
$tbl_gestores = 'gestion_usuarios';
$tbl_gestion_categorias = 'gestion_categorias';
$tbl_tipo_categoria = 'tipo_categoria';
/* ORDENES DE COMPRA */
$tcatego = 'catego'; // Tabla Categorias
$tccosto = 'ccosto'; // Tabla Centros de Costo
$tmovs = 'movs'; // Tabla Movimientos
$torden = 'orden'; // Tabla Ordenes
$tprovee = 'provee'; // Tabla Proveedores
$tobser = 'obser'; // Tabla Observaciones
$server="Driver={Client Access ODBC Driver (32-bit)};System=192.168.43.2;Uid=USRBIS;Pwd=USRBIS;"; #the name of the iSeries
$user="USRBIS"; #a valid username that will connect to the DB
$pass="USRBIS"; #a password for the username
$cia = '05';
$trestric = 'restric01';
$email_proveeduria = "mtobar@impressa.com";
$email_proveeduria2 = "czometa@impressa.com";
//$email_proveeduria2 = "erosas@impressa.com";
$email_proveeduria3 = "cornejo.karla@impressa.com";
$email_proveeduriaJefe = "hvega@impressa.com";